INSERT INTO libros (anio_publicacion, autor, editorial, titulo) VALUES
(2001, 'Gabriel García Márquez', 'Debolsillo', 'Cien años de soledad'),
(1949, 'George Orwell', 'Penguin Books', '1984'),
(1960, 'Harper Lee', 'Grand Central Publishing', 'Matar un ruiseñor'),
(1813, 'Jane Austen', 'Penguin Classics', 'Orgullo y prejuicio'),
(1937, 'J.R.R. Tolkien', 'Minotauro', 'El Hobbit'),
(1954, 'J.R.R. Tolkien', 'Minotauro', 'El Señor de los Anillos: La Comunidad del Anillo'),
(1954, 'J.R.R. Tolkien', 'Minotauro', 'El Señor de los Anillos: Las Dos Torres'),
(1955, 'J.R.R. Tolkien', 'Minotauro', 'El Señor de los Anillos: El Retorno del Rey'),
(1925, 'F. Scott Fitzgerald', 'Alfaguara', 'El Gran Gatsby'),
(1951, 'J.D. Salinger', 'Alianza Editorial', 'El guardián entre el centeno'),
(1942, 'Albert Camus', 'Alianza Editorial', 'El extranjero'),
(1985, 'Margaret Atwood', 'Salamandra', 'El cuento de la criada'),
(1967, 'Gabriel García Márquez', 'Alfaguara', 'Cien años de soledad'),
(1945, 'George Orwell', 'Debolsillo', 'Rebelión en la granja'),
(2003, 'Paulo Coelho', 'Planeta', 'El Alquimista'),
(1997, 'J.K. Rowling', 'Salamandra', 'Harry Potter y la piedra filosofal'),
(1998, 'J.K. Rowling', 'Salamandra', 'Harry Potter y la cámara secreta'),
(1999, 'J.K. Rowling', 'Salamandra', 'Harry Potter y el prisionero de Azkaban'),
(2000, 'J.K. Rowling', 'Salamandra', 'Harry Potter y el cáliz de fuego'),
(2003, 'J.K. Rowling', 'Salamandra', 'Harry Potter y la Orden del Fénix'),
(2005, 'J.K. Rowling', 'Salamandra', 'Harry Potter y el misterio del príncipe'),
(2007, 'J.K. Rowling', 'Salamandra', 'Harry Potter y las Reliquias de la Muerte'),
(1865, 'Lewis Carroll', 'Alianza Editorial', 'Alicia en el País de las Maravillas'),
(1872, 'Julio Verne', 'Alma Clásicos', 'La vuelta al mundo en 80 días'),
(1862, 'Víctor Hugo', 'Austral', 'Los miserables'),
(1984, 'Umberto Eco', 'Lumen', 'El nombre de la rosa'),
(1993, 'Isabel Allende', 'Plaza & Janés', 'La casa de los espíritus'),
(1847, 'Emily Brontë', 'Penguin Classics', 'Cumbres Borrascosas'),
(1851, 'Herman Melville', 'Austral', 'Moby Dick'),
(1982, 'Stephen King', 'Debolsillo', 'La Torre Oscura I: El pistolero'),
(1995, 'Stephen King', 'Debolsillo', 'La milla verde'),
(1974, 'Stephen King', 'Debolsillo', 'Carrie'),
(1977, 'Stephen King', 'Debolsillo', 'El resplandor'),
(1986, 'Stephen King', 'Debolsillo', 'It'),
(1999, 'Stephen King', 'Debolsillo', 'La chica que amaba a Tom Gordon'),
(2006, 'Stephen King', 'Debolsillo', 'La historia de Lisey'),
(2011, 'Stephen King', 'Debolsillo', '22/11/63'),
(2014, 'Stephen King', 'Debolsillo', 'Mr. Mercedes'),
(2017, 'Stephen King', 'Debolsillo', 'El visitante'),
(2021, 'Stephen King', 'Debolsillo', 'Billy Summers'),
(1979, 'Douglas Adams', 'Anagrama', 'La guía del autoestopista galáctico'),
(1990, 'Terry Pratchett', 'Debolsillo', 'Dioses menores'),
(2002, 'Neil Gaiman', 'Roca Editorial', 'American Gods'),
(1996, 'George R.R. Martin', 'Gigamesh', 'Juego de tronos'),
(1998, 'George R.R. Martin', 'Gigamesh', 'Choque de reyes'),
(2000, 'George R.R. Martin', 'Gigamesh', 'Tormenta de espadas'),
(2005, 'George R.R. Martin', 'Gigamesh', 'Festín de cuervos'),
(2011, 'George R.R. Martin', 'Gigamesh', 'Danza de dragones'),
(1989, 'Haruki Murakami', 'Tusquets Editores', 'Tokio Blues (Norwegian Wood)'),
(2002, 'Haruki Murakami', 'Tusquets Editores', 'Kafka en la orilla'),
(2009, 'Haruki Murakami', 'Tusquets Editores', '1Q84'),
(2017, 'Haruki Murakami', 'Tusquets Editores', 'La muerte del comendador'),
(1958, 'Truman Capote', 'Anagrama', 'Desayuno en Tiffany''s'),
(1966, 'Truman Capote', 'Anagrama', 'A sangre fría'),
(1969, 'Mario Puzo', 'Planeta', 'El Padrino'),
(1979, 'Michael Ende', 'Loqueleo', 'La historia interminable'),
(1973, 'Michael Ende', 'Loqueleo', 'Momo'),
(1943, 'Antoine de Saint-Exupéry', 'Salamandra', 'El Principito'),
(1897, 'Bram Stoker', 'Alianza Editorial', 'Drácula'),
(1818, 'Mary Shelley', 'Alianza Editorial', 'Frankenstein'),
(1886, 'Robert Louis Stevenson', 'Alianza Editorial', 'El extraño caso del Dr. Jekyll y Mr. Hyde'),
(1902, 'Arthur Conan Doyle', 'Alianza Editorial', 'El sabueso de los Baskerville'),
(1934, 'Agatha Christie', 'Booket', 'Asesinato en el Orient Express'),
(1939, 'Agatha Christie', 'Booket', 'Diez negritos'),
(1949, 'Agatha Christie', 'Booket', 'Se anuncia un asesinato'),
(1950, 'Agatha Christie', 'Booket', 'Un cadáver en la biblioteca'),
(1952, 'Agatha Christie', 'Booket', 'La ratonera y otras historias'),
(1963, 'Agatha Christie', 'Booket', 'Los cuatro grandes'),
(1969, 'Agatha Christie', 'Booket', 'En la cuerda floja'),
(1975, 'Agatha Christie', 'Booket', 'Telón: El último caso de Poirot'),
(1970, 'Gabriel García Márquez', 'Debolsillo', 'Relato de un náufrago'),
(1975, 'Gabriel García Márquez', 'Debolsillo', 'El otoño del patriarca'),
(1981, 'Gabriel García Márquez', 'Debolsillo', 'Crónica de una muerte anunciada'),
(1985, 'Gabriel García Márquez', 'Debolsillo', 'El amor en los tiempos del cólera'),
(1994, 'Gabriel García Márquez', 'Debolsillo', 'Del amor y otros demonios'),
(2004, 'Gabriel García Márquez', 'Debolsillo', 'Memoria de mis putas tristes'),
(1929, 'Erich Maria Remarque', 'Edhasa', 'Sin novedad en el frente'),
(1953, 'Ray Bradbury', 'Minotauro', 'Fahrenheit 451'),
(1950, 'Ray Bradbury', 'Minotauro', 'Crónicas Marcianas'),
(1962, 'Anthony Burgess', 'Booket', 'La naranja mecánica'),
(1992, 'Arturo Pérez-Reverte', 'Alfaguara', 'El Club Dumas'),
(1995, 'Arturo Pérez-Reverte', 'Alfaguara', 'La tabla de Flandes'),
(1998, 'Arturo Pérez-Reverte', 'Alfaguara', 'El capitán Alatriste'),
(2006, 'Arturo Pérez-Reverte', 'Alfaguara', 'El pintor de batallas'),
(2011, 'Arturo Pérez-Reverte', 'Alfaguara', 'El tango de la Guardia Vieja'),
(2015, 'Arturo Pérez-Reverte', 'Alfaguara', 'Falcó'),
(2020, 'Arturo Pérez-Reverte', 'Alfaguara', 'Línea de fuego'),
(1948, 'Truman Capote', 'Anagrama', 'Otras voces, otros ámbitos'),
(1980, 'Gabriel García Márquez', 'Debolsillo', 'El coronel no tiene quien le escriba'),
(1990, 'Almudena Grandes', 'Tusquets Editores', 'Las edades de Lulú'),
(2001, 'Carlos Ruiz Zafón', 'Planeta', 'La sombra del viento'),
(2004, 'Carlos Ruiz Zafón', 'Planeta', 'El juego del ángel'),
(2008, 'Carlos Ruiz Zafón', 'Planeta', 'El prisionero del cielo'),
(2016, 'Carlos Ruiz Zafón', 'Planeta', 'El laberinto de los espíritus'),
(1996, 'Javier Marías', 'Alfaguara', 'Corazón tan blanco'),
(2004, 'Javier Marías', 'Alfaguara', 'Tu rostro mañana 1: Fiebre y lanza'),
(2007, 'Javier Marías', 'Alfaguara', 'Tu rostro mañana 2: Baile y sueño'),
(2009, 'Javier Marías', 'Alfaguara', 'Tu rostro mañana 3: Veneno y sombra y adiós'),
(1980, 'Stephen King', 'Debolsillo', 'Ojos de fuego'),
(1982, 'Stephen King', 'Debolsillo', 'La zona muerta'),
(1987, 'Stephen King', 'Debolsillo', 'Misery'),
(1994, 'Stephen King', 'Debolsillo', 'Insomnia'),
(2001, 'Stephen King', 'Debolsillo', 'El cazador de sueños'),
(2008, 'Stephen King', 'Debolsillo', 'Duma Key'),
(2012, 'Stephen King', 'Debolsillo', 'Doctor Sueño'),
(2018, 'Stephen King', 'Debolsillo', 'Elevación'),
(2019, 'Stephen King', 'Debolsillo', 'El instituto'),
(2022, 'Stephen King', 'Debolsillo', 'Cuentos de hadas'),
(1932, 'Aldous Huxley', 'Debolsillo', 'Un mundo feliz'),
(1973, 'Arthur C. Clarke', 'Minotauro', 'Cita con Rama'),
(1968, 'Philip K. Dick', 'Minotauro', '¿Sueñan los androides con ovejas eléctricas?'),
(1984, 'William Gibson', 'Minotauro', 'Neuromante'),
(1992, 'Neal Stephenson', 'Minotauro', 'Snow Crash'),
(1995, 'José Saramago', 'Alfaguara', 'Ensayo sobre la ceguera'),
(1986, 'José Saramago', 'Alfaguara', 'La balsa de piedra'),
(1997, 'José Saramago', 'Alfaguara', 'Todos los nombres'),
(2000, 'José Saramago', 'Alfaguara', 'La caverna'),
(2004, 'José Saramago', 'Alfaguara', 'Las intermitencias de la muerte'),
(2009, 'José Saramago', 'Alfaguara', 'Caín'),
(1965, 'Frank Herbert', 'Debolsillo', 'Dune'),
(1969, 'Kurt Vonnegut Jr.', 'Anagrama', 'Matadero Cinco'),
(1996, 'Philip Pullman', 'Roca Editorial', 'Luces del Norte'),
(1997, 'Philip Pullman', 'Roca Editorial', 'La daga'),
(2000, 'Philip Pullman', 'Roca Editorial', 'El catalejo lacado'),
(2017, 'Philip Pullman', 'Roca Editorial', 'La Bella Salvaje'),
(1844, 'Alexandre Dumas', 'Austral', 'Los tres mosqueteros'),
(1844, 'Alexandre Dumas', 'Austral', 'El conde de Montecristo'),
(1883, 'Robert Louis Stevenson', 'Alianza Editorial', 'La isla del tesoro'),
(1911, 'Frances Hodgson Burnett', 'Penguin Clásicos', 'El jardín secreto'),
(1908, 'Lucy Maud Montgomery', 'Austral', 'Ana de las Tejas Verdes'),
(1926, 'A.A. Milne', 'Alianza Editorial', 'Winnie the Pooh'),
(1938, 'T.H. White', 'Minotauro', 'Camelot'),
(1949, 'Antoine de Saint-Exupéry', 'Salamandra', 'Tierra de hombres'),
(1961, 'Roald Dahl', 'Alfaguara', 'James y el melocotón gigante'),
(1964, 'Roald Dahl', 'Alfaguara', 'Charlie y la fábrica de chocolate'),
(1970, 'Roald Dahl', 'Alfaguara', 'El Superzorro'),
(1982, 'Roald Dahl', 'Alfaguara', 'El gran gigante bonachón'),
(1983, 'Roald Dahl', 'Alfaguara', 'Las brujas'),
(1988, 'Roald Dahl', 'Alfaguara', 'Matilda'),
(1976, 'Anne Rice', 'B de Bolsillo', 'Entrevista con el vampiro'),
(1985, 'Patrick Süskind', 'Seix Barral', 'El perfume'),
(1986, 'Scott Turow', 'Plaza & Janés', 'Presunto inocente'),
(1987, 'Tom Wolfe', 'Anagrama', 'La hoguera de las vanidades'),
(1988, 'Salman Rushdie', 'Debolsillo', 'Los versos satánicos'),
(1991, 'Bret Easton Ellis', 'Debolsillo', 'American Psycho'),
(1992, 'Donna Tartt', 'Lumen', 'El secreto'),
(1994, 'Laura Esquivel', 'Debolsillo', 'Como agua para chocolate'),
(1995, 'Alessandro Baricco', 'Anagrama', 'Seda'),
(1999, 'Jonathan Franzen', 'Salamandra', 'Las correcciones'),
(2000, 'Yann Martel', 'Debolsillo', 'Vida de Pi'),
(2001, 'Zadie Smith', 'Salamandra', 'Dientes blancos'),
(2003, 'Audrey Niffenegger', 'Suma de Letras', 'La mujer del viajero en el tiempo'),
(2005, 'Stieg Larsson', 'Destino', 'Los hombres que no amaban a las mujeres'),
(2006, 'Stieg Larsson', 'Destino', 'La chica que soñaba con una cerilla y un bidón de gasolina'),
(2007, 'Stieg Larsson', 'Destino', 'La reina en el palacio de las corrientes de aire'),
(2009, 'Kathryn Stockett', 'Penguin Random House', 'Criadas y señoras'),
(2010, 'Suzanne Collins', 'RBA', 'Los Juegos del Hambre'),
(2011, 'Suzanne Collins', 'RBA', 'En llamas'),
(2012, 'Suzanne Collins', 'RBA', 'Sinsajo'),
(2012, 'Gillian Flynn', 'Salamandra', 'Perdida'),
(2014, 'Paula Hawkins', 'Planeta', 'La chica del tren'),
(2016, 'Fernando Aramburu', 'Tusquets Editores', 'Patria'),
(2017, 'Elísabet Benavent', 'Suma de Letras', 'En los zapatos de Valeria'),
(2018, 'Jojo Moyes', 'Debolsillo', 'Yo antes de ti'),
(2019, 'Megan Maxwell', 'Planeta', 'Pídeme lo que quieras'),
(2020, 'Delia Owens', 'Penguin Random House', 'La chica salvaje'),
(2021, 'Matt Haig', 'Planeta', 'La biblioteca de la medianoche'),
(2022, 'Colleen Hoover', 'Atria Books', 'Romper el círculo'),
(2023, 'Rebecca Yarros', 'Umbriel', 'Alas de Sangre'),
(1890, 'Oscar Wilde', 'Alianza Editorial', 'El retrato de Dorian Gray'),
(1891, 'Arthur Conan Doyle', 'Alianza Editorial', 'Estudio en escarlata'),
(1892, 'Arthur Conan Doyle', 'Alianza Editorial', 'Las aventuras de Sherlock Holmes'),
(1894, 'Arthur Conan Doyle', 'Alianza Editorial', 'Las memorias de Sherlock Holmes'),
(1896, 'H.G. Wells', 'Alianza Editorial', 'La isla del Dr. Moreau'),
(1897, 'H.G. Wells', 'Alianza Editorial', 'El hombre invisible'),
(1898, 'H.G. Wells', 'Alianza Editorial', 'La guerra de los mundos'),
(1900, 'Joseph Conrad', 'Debolsillo', 'El corazón de las tinieblas'),
(1903, 'Jack London', 'Alianza Editorial', 'La llamada de lo salvaje'),
(1906, 'Jack London', 'Alianza Editorial', 'Colmillo blanco'),
(1922, 'James Joyce', 'Cátedra', 'Ulises'),
(1924, 'Thomas Mann', 'Edhasa', 'La montaña mágica'),
(1927, 'Virginia Woolf', 'Alianza Editorial', 'Al faro'),
(1928, 'Virginia Woolf', 'Alianza Editorial', 'Orlando'),
(1930, 'Dashiell Hammett', 'Debolsillo', 'El halcón maltés'),
(1936, 'Dale Carnegie', 'Vergara', 'Cómo ganar amigos e influir sobre las personas'),
(1939, 'John Steinbeck', 'Alianza Editorial', 'Las uvas de la ira'),
(1940, 'Ernest Hemingway', 'Debolsillo', 'Por quién doblan las campanas'),
(1952, 'Ernest Hemingway', 'Debolsillo', 'El viejo y el mar'),
(1961, 'Joseph Heller', 'Debolsillo', 'Trampa-22'),
(1966, 'Ken Kesey', 'Debolsillo', 'Alguien voló sobre el nido del cuco'),
(1978, 'John Irving', 'Tusquets Editores', 'El mundo según Garp'),
(1979, 'William Styron', 'Debolsillo', 'La decisión de Sophie'),
(1983, 'Milan Kundera', 'Tusquets Editores', 'La insoportable levedad del ser'),
(1989, 'Amy Tan', 'Planeta', 'El club de la buena estrella'),
(1991, 'Cormac McCarthy', 'Random House', 'Todos los caballos bellos'),
(1994, 'Louis de Bernières', 'Planeta', 'La mandolina del Capitán Corelli'),
(1996, 'David Foster Wallace', 'Debolsillo', 'La broma infinita'),
(1997, 'Don DeLillo', 'Seix Barral', 'Submundo'),
(1998, 'Jeffrey Eugenides', 'Anagrama', 'Las vírgenes suicidas'),
(2000, 'Dave Eggers', 'Debolsillo', 'Una obra de genio deslumbrante'),
(2002, 'Jonathan Safran Foer', 'Salamandra', 'Todo está iluminado'),
(2004, 'Marilynne Robinson', 'Errata Naturae', 'Gilead'),
(2005, 'Khaled Hosseini', 'Salamandra', 'Mil soles espléndidos'),
(2006, 'Cormac McCarthy', 'Random House', 'La carretera'),
(2007, 'Junot Díaz', 'Literatura Random House', 'La maravillosa vida breve de Óscar Wao'),
(2008, 'Roberto Bolaño', 'Anagrama', '2666'),
(2009, 'Hilary Mantel', 'Ediciones B', 'En la corte del lobo'),
(2010, 'Jonathan Franzen', 'Salamandra', 'Libertad'),
(2011, 'George Saunders', 'Salamandra', 'Diez de diciembre'),
(2013, 'Donna Tartt', 'Lumen', 'El jilguero'),
(2014, 'Anthony Doerr', 'Suma de Letras', 'La luz que no puedes ver'),
(2015, 'Kazuo Ishiguro', 'Anagrama', 'El gigante enterrado'),
(2016, 'Paul Kalanithi', 'Sexto Piso', 'Cuando el aliento se convierte en aire'),
(2018, 'Tara Westover', 'Penguin Random House', 'Educated'),
(2019, 'Valeria Luiselli', 'Literatura Random House', 'Desierto sonoro'),
(2020, 'Brit Bennett', 'Libros del Asteroide', 'La mitad evanescente'),
(2021, 'Maggie Shipstead', 'Literatura Random House', 'Gran círculo'),
(2022, 'Jonathan Franzen', 'Salamandra', 'Encrucijadas'),
(2023, 'Hernan Diaz', 'Anagrama', 'Fortuna'),
(1996, 'E.L. James', 'Grijalbo', 'Cincuenta sombras de Grey'),
(2012, 'John Green', 'Nube de Tinta', 'Bajo la misma estrella'),
(2013, 'Veronica Roth', 'RBA', 'Divergente'),
(2014, 'Rick Riordan', 'Salamandra', 'Percy Jackson y el ladrón del rayo'),
(2015, 'Rainbow Rowell', 'Alfaguara', 'Eleanor & Park'),
(2016, 'Cassandra Clare', 'Destino', 'Ciudad de Hueso'),
(2017, 'Marie Lu', 'Hidra', 'Legend'),
(2018, 'Leigh Bardugo', 'Hidra', 'Seis de Cuervos'),
(2019, 'Holly Black', 'Hidra', 'El Príncipe Cruel'),
(2020, 'Sarah J. Maas', 'Planeta', 'Una corte de rosas y espinas'),
(2021, 'Brandon Sanderson', 'Nova', 'Elantris'),
(2022, 'Brandon Sanderson', 'Nova', 'Nacidos de la bruma: El Imperio Final'),
(2023, 'Brandon Sanderson', 'Nova', 'Nacidos de la bruma: El Pozo de la Ascensión'),
(2024, 'Brandon Sanderson', 'Nova', 'Nacidos de la bruma: El Héroe de las Eras'),
(1987, 'R.A. Salvatore', 'Timunmas', 'El Valle del Viento Helado'),
(1988, 'R.A. Salvatore', 'Timunmas', 'La morada del guardián'),
(1989, 'R.A. Salvatore', 'Timunmas', 'El estigma de Drizzt'),
(1990, 'R.A. Salvatore', 'Timunmas', 'El exilio de Drizzt'),
(1991, 'R.A. Salvatore', 'Timunmas', 'El Refugio'),
(1992, 'Terry Brooks', 'Timunmas', 'La espada de Shannara'),
(1993, 'Terry Brooks', 'Timunmas', 'Las piedras élficas de Shannara'),
(1994, 'Terry Brooks', 'Timunmas', 'El canto élfico de Shannara'),
(1995, 'Anne McCaffrey', 'Timunmas', 'El vuelo del dragón'),
(1996, 'Anne McCaffrey', 'Timunmas', 'La búsqueda del dragón'),
(1997, 'Anne McCaffrey', 'Timunmas', 'El dragón blanco'),
(1998, 'Robin Hobb', 'Plaza & Janés', 'Asesino real'),
(1999, 'Robin Hobb', 'Plaza & Janés', 'La búsqueda del asesino'),
(2000, 'Robin Hobb', 'Plaza & Janés', 'La nave de la magia'),
(2001, 'Robin Hobb', 'Plaza & Janés', 'La nave de los destinos'),
(2002, 'Robin Hobb', 'Plaza & Janés', 'La nave de los sueños'),
(2003, 'Ursula K. Le Guin', 'Minotauro', 'Un mago de Terramar'),
(2004, 'Ursula K. Le Guin', 'Minotauro', 'Las tumbas de Atuan'),
(2005, 'Ursula K. Le Guin', 'Minotauro', 'La costa más lejana'),
(2006, 'Ursula K. Le Guin', 'Minotauro', 'Tehanu'),
(2007, 'Ursula K. Le Guin', 'Minotauro', 'En el otro viento'),
(2008, 'Stephenie Meyer', 'Alfaguara', 'Crepúsculo'),
(2009, 'Stephenie Meyer', 'Alfaguara', 'Luna Nueva'),
(2010, 'Stephenie Meyer', 'Alfaguara', 'Eclipse'),
(2011, 'Stephenie Meyer', 'Alfaguara', 'Amanecer'),
(2012, 'Cassandra Clare', 'Destino', 'Ciudad de Ceniza'),
(2013, 'Cassandra Clare', 'Destino', 'Ciudad de Cristal'),
(2014, 'Cassandra Clare', 'Destino', 'Ciudad de los Ángeles Caídos'),
(2015, 'Cassandra Clare', 'Destino', 'Ciudad de las Almas Perdidas'),
(2016, 'Cassandra Clare', 'Destino', 'Ciudad del Fuego Celestial'),
(2017, 'Leigh Bardugo', 'Hidra', 'Asedio y Tormenta'),
(2018, 'Leigh Bardugo', 'Hidra', 'Ruina y Ascenso'),
(2019, 'Leigh Bardugo', 'Hidra', 'Reino de ladrones'),
(2020, 'Holly Black', 'Hidra', 'El Rey Malvado'),
(2021, 'Holly Black', 'Hidra', 'La Reina del Aire y la Oscuridad'),
(2022, 'Sarah J. Maas', 'Planeta', 'Una corte de niebla y furia'),
(2023, 'Sarah J. Maas', 'Planeta', 'Una corte de alas y ruina'),
(2024, 'Sarah J. Maas', 'Planeta', 'Una corte de hielo y estrellas'),
(1990, 'Terry Pratchett', 'Debolsillo', 'Guardias! ¿Guardias!'),
(1991, 'Terry Pratchett', 'Debolsillo', 'Deidad ambulatoria'),
(1992, 'Terry Pratchett', 'Debolsillo', 'Hombres de armas'),
(1993, 'Terry Pratchett', 'Debolsillo', 'Soul Music'),
(1994, 'Terry Pratchett', 'Debolsillo', 'Interesantes tiempos'),
(1995, 'Terry Pratchett', 'Debolsillo', 'Mascarada'),
(1996, 'Terry Pratchett', 'Debolsillo', 'Pies de barro'),
(1997, 'Terry Pratchett', 'Debolsillo', 'Papá Puerco'),
(1998, 'Terry Pratchett', 'Debolsillo', 'Jingo'),
(1999, 'Terry Pratchett', 'Debolsillo', 'El quinto elefante'),
(2000, 'Terry Pratchett', 'Debolsillo', 'La verdad'),
(2001, 'Terry Pratchett', 'Debolsillo', 'Ronda de Noche'),
(2002, 'Terry Pratchett', 'Debolsillo', 'El País de los Duendes'),
(2003, 'Terry Pratchett', 'Debolsillo', 'Monstruos de hielo'),
(2004, 'Terry Pratchett', 'Debolsillo', 'Cartas a un pequeño dios'),
(2005, 'Terry Pratchett', 'Debolsillo', '¡Zas!'),
(2006, 'Terry Pratchett', 'Debolsillo', 'Dinero en efectivo'),
(2007, 'Terry Pratchett', 'Debolsillo', 'La Bolsa de los Huesos'),
(2008, 'Terry Pratchett', 'Debolsillo', 'Un sombrero lleno de estrellas'),
(2009, 'Terry Pratchett', 'Debolsillo', 'El arte de la hechicería'),
(2010, 'Terry Pratchett', 'Debolsillo', 'El factor Vudú'),
(2011, 'Terry Pratchett', 'Debolsillo', 'Snuff'),
(2012, 'Terry Pratchett', 'Debolsillo', 'A.P.L. (La Liga del Pueblo Libre)'),
(2013, 'Terry Pratchett', 'Debolsillo', 'El País de las Maravillas'),
(2014, 'Terry Pratchett', 'Debolsillo', 'La corona del pastor'),
(1957, 'Dr. Seuss', 'Penguin Random House', 'El Grinch'),
(1960, 'Dr. Seuss', 'Penguin Random House', 'Huevos verdes con jamón'),
(1971, 'Dr. Seuss', 'Penguin Random House', 'El Lorax'),
(1984, 'Shel Silverstein', 'HarperCollins', 'Donde termina la acera'),
(1996, 'Shel Silverstein', 'HarperCollins', 'Un árbol generoso'),
(2004, 'Mo Willems', 'Hyperion Books', 'No dejes que la paloma conduzca el autobús'),
(2007, 'Jeff Kinney', 'Molino', 'Diario de Greg 1: Un pringao total'),
(2008, 'Jeff Kinney', 'Molino', 'Diario de Greg 2: La ley de Rodrick'),
(2009, 'Jeff Kinney', 'Molino', 'Diario de Greg 3: ¡Esto es el colmo!'),
(2010, 'Jeff Kinney', 'Molino', 'Diario de Greg 4: Días de perros'),
(2011, 'Jeff Kinney', 'Molino', 'Diario de Greg 5: La cruda realidad'),
(2012, 'Jeff Kinney', 'Molino', 'Diario de Greg 6: Atrapados en la nieve'),
(2013, 'Jeff Kinney', 'Molino', 'Diario de Greg 7: Tercero y a la calle'),
(2014, 'Jeff Kinney', 'Molino', 'Diario de Greg 8: Carretera y manta'),
(2015, 'Jeff Kinney', 'Molino', 'Diario de Greg 9: El libro de las vacaciones'),
(2016, 'Jeff Kinney', 'Molino', 'Diario de Greg 10: Viejos tiempos'),
(2017, 'Jeff Kinney', 'Molino', 'Diario de Greg 11: Doble o nada'),
(2018, 'Jeff Kinney', 'Molino', 'Diario de Greg 12: Descerebrados'),
(2019, 'Jeff Kinney', 'Molino', 'Diario de Greg 13: Frío fatal'),
(2020, 'Jeff Kinney', 'Molino', 'Diario de Greg 14: Bota la bola'),
(2021, 'Jeff Kinney', 'Molino', 'Diario de Greg 15: Tocado y hundido'),
(2022, 'Jeff Kinney', 'Molino', 'Diario de Greg 16: El número uno'),
(2023, 'Jeff Kinney', 'Molino', 'Diario de Greg 17: Cabezazo de oro'),
(2024, 'Jeff Kinney', 'Molino', 'Diario de Greg 18: Sin salida'),
(1997, 'Dav Pilkey', 'Scholastic', 'Capitán Calzoncillos: Las aventuras del Capitán Calzoncillos'),
(1999, 'Dav Pilkey', 'Scholastic', 'Capitán Calzoncillos y el ataque de los inodoros parlantes'),
(2000, 'Dav Pilkey', 'Scholastic', 'Capitán Calzoncillos y la invasión de los perversos extraterrestres'),
(2002, 'Dav Pilkey', 'Scholastic', 'Capitán Calzoncillos y la terrible venganza del Profesor Pipicaca'),
(2003, 'Dav Pilkey', 'Scholastic', 'Capitán Calzoncillos y la furia de la Mujer Melena'),
(2005, 'Dav Pilkey', 'Scholastic', 'Capitán Calzoncillos y el Bigotudo del Mal'),
(2006, 'Dav Pilkey', 'Scholastic', 'Capitán Calzoncillos y la saga del Sorbe-Bolas'),
(2008, 'Dav Pilkey', 'Scholastic', 'Capitán Calzoncillos y las tretas del tirano Tripas Sucias'),
(2010, 'Dav Pilkey', 'Scholastic', 'Capitán Calzoncillos y el repugnante regreso del Capitán Calzoncillos'),
(2012, 'Dav Pilkey', 'Scholastic', 'Capitán Calzoncillos y la venganza del Bicho Malvado'),
(2014, 'Dav Pilkey', 'Scholastic', 'Capitán Calzoncillos y el ataque de los monstruos mutantes'),
(2016, 'Dav Pilkey', 'Scholastic', 'Capitán Calzoncillos y el baño del terror'),
(2017, 'Dav Pilkey', 'Scholastic', 'Dog Man: Un policía muy perro'),
(2018, 'Dav Pilkey', 'Scholastic', 'Dog Man: Desatado'),
(2019, 'Dav Pilkey', 'Scholastic', 'Dog Man: La historia de dos gatitos'),
(2020, 'Dav Pilkey', 'Scholastic', 'Dog Man: El señor de las pulgas'),
(2021, 'Dav Pilkey', 'Scholastic', 'Dog Man: La bola salvaje'),
(2022, 'Dav Pilkey', 'Scholastic', 'Dog Man: El ladrido de la llamada'),
(2023, 'Dav Pilkey', 'Scholastic', 'Dog Man: La venganza del Grinch'),
(2024, 'Dav Pilkey', 'Scholastic', 'Dog Man: Un cuento de dos ciudades'),
(1987, 'Mem Fox', 'HarperCollins', 'Diez pequeños conejitos'),
(1994, 'Eric Carle', 'Kókinos', 'La oruga muy hambrienta'),
(1969, 'Eric Carle', 'Kókinos', 'Oso Pardo, Oso Pardo, ¿qué ves?'),
(1995, 'Marcus Pfister', 'Nordica Libros', 'El pez arcoíris'),
(1989, 'Bill Martin Jr.', 'Kókinos', 'El oso pardo, oso pardo, ¿qué ves?'),
(1991, 'Mem Fox', 'HarperCollins', 'El conejito que no quería dormir'),
(1992, 'Judith Kerr', 'Andana Editorial', 'El tigre que vino a tomar el té'),
(1993, 'Julia Donaldson', 'Macmillan Children''s Books', 'El Grúfalo'),
(1999, 'Julia Donaldson', 'Macmillan Children''s Books', 'La Hija del Grúfalo'),
(2002, 'Julia Donaldson', 'Macmillan Children''s Books', 'El Gruffaló y su hija'),
(2004, 'Julia Donaldson', 'Macmillan Children''s Books', 'La Cueva del Grúfalo'),
(2005, 'Julia Donaldson', 'Macmillan Children''s Books', 'El bastón mágico'),
(2006, 'Julia Donaldson', 'Macmillan Children''s Books', 'La ballena y el caracol'),
(2007, 'Julia Donaldson', 'Macmillan Children''s Books', 'El topo que quería saber quién se había hecho aquello en su cabeza'),
(2008, 'Julia Donaldson', 'Macmillan Children''s Books', 'El dragón chiflado'),
(2009, 'Julia Donaldson', 'Macmillan Children''s Books', 'La ratita presumida'),
(2010, 'Julia Donaldson', 'Macmillan Children''s Books', 'El super gusano'),
(2011, 'Julia Donaldson', 'Macmillan Children''s Books', 'El cocodrilo que no quería ser verde'),
(2012, 'Julia Donaldson', 'Macmillan Children''s Books', 'El pequeño dragón que no quería volar'),
(2013, 'Julia Donaldson', 'Macmillan Children''s Books', 'El caracol y la ballena'),
(2014, 'Julia Donaldson', 'Macmillan Children''s Books', 'Zog'),
(2015, 'Julia Donaldson', 'Macmillan Children''s Books', 'El superzorro y la familia de la cueva'),
(2016, 'Julia Donaldson', 'Macmillan Children''s Books', 'El árbol de los deseos'),
(2017, 'Julia Donaldson', 'Macmillan Children''s Books', 'El búho al que le daba miedo la oscuridad'),
(2018, 'Julia Donaldson', 'Macmillan Children''s Books', 'El gigante Gruñón'),
(2019, 'Julia Donaldson', 'Macmillan Children''s Books', 'La escoba voladora'),
(2020, 'Julia Donaldson', 'Macmillan Children''s Books', 'El renacuajo que no quería ser rana'),
(2021, 'Julia Donaldson', 'Macmillan Children''s Books', 'El pingüino que no quería volar'),
(2022, 'Julia Donaldson', 'Macmillan Children''s Books', 'La luciérnaga que no quería brillar'),
(2023, 'Julia Donaldson', 'Macmillan Children''s Books', 'El koala que no quería abrazar'),
(2024, 'Julia Donaldson', 'Macmillan Children''s Books', 'El perezoso que no quería dormir'),
(1976, 'Judith Viorst', 'HarperCollins', 'Alexander y el día terrible, horrible, espantoso, horroroso'),
(1987, 'Chris Van Allsburg', 'Houghton Mifflin Harcourt', 'Jumanji'),
(1981, 'Chris Van Allsburg', 'Houghton Mifflin Harcourt', 'El expreso polar'),
(1985, 'Laura Numeroff', 'HarperCollins', 'Si le das una galleta a un ratón'),
(1998, 'Karma Wilson', 'Simon & Schuster Books for Young Readers', 'Oso pardo, oso pardo, ¿qué ves?'),
(2005, 'Doreen Cronin', 'Simon & Schuster Books for Young Readers', 'Vacas locas'),
(2000, 'Mem Fox', 'HarperCollins', 'El conejito que no quería dormir'),
(2001, 'Robert Munsch', 'Annick Press', 'Amarillo, el libro de los colores'),
(2002, 'David Shannon', 'Scholastic', 'No, David!'),
(2003, 'Todd Parr', 'Little, Brown Books for Young Readers', 'El libro de la paz'),
(2004, 'Mies van Hout', 'Lemniscaat', 'Feliz'),
(2005, 'Kobi Yamada', 'Compendium', '¿Qué harías con una idea?'),
(2006, 'Oliver Jeffers', 'HarperCollins', 'Cómo atrapar una estrella'),
(2007, 'Oliver Jeffers', 'HarperCollins', 'Perdido y encontrado'),
(2008, 'Oliver Jeffers', 'HarperCollins', 'El increíble niño comelibros'),
(2009, 'Oliver Jeffers', 'HarperCollins', 'Esto y aquello'),
(2010, 'Oliver Jeffers', 'HarperCollins', 'El corazón y la botella'),
(2011, 'Oliver Jeffers', 'HarperCollins', 'El gran diseño de un árbol'),
(2012, 'Oliver Jeffers', 'HarperCollins', 'Arriba y abajo'),
(2013, 'Oliver Jeffers', 'HarperCollins', 'Aquí estamos: Notas para vivir en el planeta Tierra'),
(2014, 'Oliver Jeffers', 'HarperCollins', 'El cuaderno de dibujos de El increíble niño comelibros'),
(2015, 'Oliver Jeffers', 'HarperCollins', 'El niño que se robó la luna'),
(2016, 'Oliver Jeffers', 'HarperCollins', 'Un camino a casa'),
(2017, 'Oliver Jeffers', 'HarperCollins', 'La pequeña criatura y el gran lío'),
(2018, 'Oliver Jeffers', 'HarperCollins', 'El niño que amaba el mar'),
(2019, 'Oliver Jeffers', 'HarperCollins', 'El lobo con botas'),
(2020, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un amigo'),
(2021, 'Oliver Jeffers', 'HarperCollins', 'El niño que no quería irse a la cama'),
(2022, 'Oliver Jeffers', 'HarperCollins', 'El misterio de la luna robada'),
(2023, 'Oliver Jeffers', 'HarperCollins', 'El niño que encontró un dinosaurio'),
(2024, 'Oliver Jeffers', 'HarperCollins', 'El viaje del increíble niño comelibros'),
(1963, 'Maurice Sendak', 'HarperCollins', 'Donde viven los monstruos'),
(1967, 'Leo Lionni', 'Kókinos', 'Frederick'),
(1973, 'Vera B. Williams', 'Greenwillow Books', 'Un sillón para mi mamá'),
(1982, 'Crockett Johnson', 'HarperCollins', 'Harold y el lápiz de cera morado'),
(1983, 'Margery Williams Bianco', 'HarperCollins', 'El conejo de terciopelo'),
(1984, 'Audrey Wood', 'Harcourt Brace Jovanovich', 'El rey Midas y el toque de oro'),
(1985, 'Jan Brett', 'G.P. Putnam''s Sons', 'El sombrero de la nieve'),
(1986, 'Kevin Henkes', 'Greenwillow Books', 'Crisantemo'),
(1987, 'Jane Yolen', 'Harcourt Brace Jovanovich', 'El búho que no quería dormir'),
(1988, 'Bill Peet', 'Houghton Mifflin', 'El cocodrilo que no quería ser verde'),
(1989, 'Lynn Munsinger', 'HarperCollins', 'El osito que quería volar'),
(1990, 'Mem Fox', 'HarperCollins', 'La gallina que no quería poner huevos'),
(1991, 'Kevin Henkes', 'Greenwillow Books', 'Lilly y su bolso de plástico morado'),
(1992, 'Eric Carle', 'Kókinos', 'De la cabeza a los pies'),
(1993, 'Bernard Waber', 'Houghton Mifflin Harcourt', 'Lyle, Lyle, cocodrilo'),
(1994, 'Leo Lionni', 'Kókinos', 'Pez, pez, pez'),
(1995, 'Laura Numeroff', 'HarperCollins', 'Si le das un pancake a un cerdo'),
(1996, 'Mo Willems', 'Hyperion Books', 'El pato que no quería volar'),
(1997, 'Karma Wilson', 'Simon & Schuster Books for Young Readers', 'Oso está dormido'),
(1998, 'Doreen Cronin', 'Simon & Schuster Books for Young Readers', 'Clic, Clac, Muu: Vacas que escriben a máquina'),
(1999, 'Mem Fox', 'HarperCollins', '¿Dónde está mi mamá?'),
(2000, 'Robert Munsch', 'Annick Press', 'El papel de los colores'),
(2001, 'David Shannon', 'Scholastic', '¡Grita, David!'),
(2002, 'Todd Parr', 'Little, Brown Books for Young Readers', 'El libro del amor'),
(2003, 'Mies van Hout', 'Lemniscaat', 'Yo soy un animal'),
(2004, 'Kobi Yamada', 'Compendium', '¿Qué harías con un problema?'),
(2005, 'Oliver Jeffers', 'HarperCollins', 'El niño de los lápices de colores'),
(2006, 'Oliver Jeffers', 'HarperCollins', 'El niño que no quería dormir'),
(2007, 'Oliver Jeffers', 'HarperCollins', 'El niño que no quería irse a la cama'),
(2008, 'Oliver Jeffers', 'HarperCollins', 'El niño que amaba los libros'),
(2009, 'Oliver Jeffers', 'HarperCollins', 'El niño que se encontró con un dinosaurio'),
(2010, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería volar'),
(2011, 'Oliver Jeffers', 'HarperCollins', 'El niño que no quería ser un perro'),
(2012, 'Oliver Jeffers', 'HarperCollins', 'El niño que no quería un amigo'),
(2013, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería una nube'),
(2014, 'Oliver Jeffers', 'HarperCollins', 'El niño que no quería comer'),
(2015, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un cuento'),
(2016, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un sombrero'),
(2017, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería una casa'),
(2018, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería una bicicleta'),
(2019, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un perro'),
(2020, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un gato'),
(2021, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un pez'),
(2022, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un pájaro'),
(2023, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un conejo'),
(2024, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un ratón'),
(1990, 'Mem Fox', 'HarperCollins', 'La gallina que no quería poner huevos'),
(1991, 'Kevin Henkes', 'Greenwillow Books', 'Lilly y su bolso de plástico morado'),
(1992, 'Eric Carle', 'Kókinos', 'De la cabeza a los pies'),
(1993, 'Bernard Waber', 'Houghton Mifflin Harcourt', 'Lyle, Lyle, cocodrilo'),
(1994, 'Leo Lionni', 'Kókinos', 'Pez, pez, pez'),
(1995, 'Laura Numeroff', 'HarperCollins', 'Si le das un pancake a un cerdo'),
(1996, 'Mo Willems', 'Hyperion Books', 'El pato que no quería volar'),
(1997, 'Karma Wilson', 'Simon & Schuster Books for Young Readers', 'Oso está dormido'),
(1998, 'Doreen Cronin', 'Simon & Schuster Books for Young Readers', 'Clic, Clac, Muu: Vacas que escriben a máquina'),
(1999, 'Mem Fox', 'HarperCollins', '¿Dónde está mi mamá?'),
(2000, 'Robert Munsch', 'Annick Press', 'El papel de los colores'),
(2001, 'David Shannon', 'Scholastic', '¡Grita, David!'),
(2002, 'Todd Parr', 'Little, Brown Books for Young Readers', 'El libro del amor'),
(2003, 'Mies van Hout', 'Lemniscaat', 'Yo soy un animal'),
(2004, 'Kobi Yamada', 'Compendium', '¿Qué harías con un problema?'),
(2005, 'Oliver Jeffers', 'HarperCollins', 'El niño de los lápices de colores'),
(2006, 'Oliver Jeffers', 'HarperCollins', 'El niño que no quería dormir'),
(2007, 'Oliver Jeffers', 'HarperCollins', 'El niño que no quería irse a la cama'),
(2008, 'Oliver Jeffers', 'HarperCollins', 'El niño que amaba los libros'),
(2009, 'Oliver Jeffers', 'HarperCollins', 'El niño que se encontró con un dinosaurio'),
(2010, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería volar'),
(2011, 'Oliver Jeffers', 'HarperCollins', 'El niño que no quería ser un perro'),
(2012, 'Oliver Jeffers', 'HarperCollins', 'El niño que no quería un amigo'),
(2013, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería una nube'),
(2014, 'Oliver Jeffers', 'HarperCollins', 'El niño que no quería comer'),
(2015, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un cuento'),
(2016, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un sombrero'),
(2017, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería una casa'),
(2018, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería una bicicleta'),
(2019, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un perro'),
(2020, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un gato'),
(2021, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un pez'),
(2022, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un pájaro'),
(2023, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un conejo'),
(2024, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un ratón'),
(1990, 'Mem Fox', 'HarperCollins', 'La gallina que no quería poner huevos'),
(1991, 'Kevin Henkes', 'Greenwillow Books', 'Lilly y su bolso de plástico morado'),
(1992, 'Eric Carle', 'Kókinos', 'De la cabeza a los pies'),
(1993, 'Bernard Waber', 'Houghton Mifflin Harcourt', 'Lyle, Lyle, cocodrilo'),
(1994, 'Leo Lionni', 'Kókinos', 'Pez, pez, pez'),
(1995, 'Laura Numeroff', 'HarperCollins', 'Si le das un pancake a un cerdo'),
(1996, 'Mo Willems', 'Hyperion Books', 'El pato que no quería volar'),
(1997, 'Karma Wilson', 'Simon & Schuster Books for Young Readers', 'Oso está dormido'),
(1998, 'Doreen Cronin', 'Simon & Schuster Books for Young Readers', 'Clic, Clac, Muu: Vacas que escriben a máquina'),
(1999, 'Mem Fox', 'HarperCollins', '¿Dónde está mi mamá?'),
(2000, 'Robert Munsch', 'Annick Press', 'El papel de los colores'),
(2001, 'David Shannon', 'Scholastic', '¡Grita, David!'),
(2002, 'Todd Parr', 'Little, Brown Books for Young Readers', 'El libro del amor'),
(2003, 'Mies van Hout', 'Lemniscaat', 'Yo soy un animal'),
(2004, 'Kobi Yamada', 'Compendium', '¿Qué harías con un problema?'),
(2005, 'Oliver Jeffers', 'HarperCollins', 'El niño de los lápices de colores'),
(2006, 'Oliver Jeffers', 'HarperCollins', 'El niño que no quería dormir'),
(2007, 'Oliver Jeffers', 'HarperCollins', 'El niño que no quería irse a la cama'),
(2008, 'Oliver Jeffers', 'HarperCollins', 'El niño que amaba los libros'),
(2009, 'Oliver Jeffers', 'HarperCollins', 'El niño que se encontró con un dinosaurio'),
(2010, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería volar'),
(2011, 'Oliver Jeffers', 'HarperCollins', 'El niño que no quería ser un perro'),
(2012, 'Oliver Jeffers', 'HarperCollins', 'El niño que no quería un amigo'),
(2013, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería una nube'),
(2014, 'Oliver Jeffers', 'HarperCollins', 'El niño que no quería comer'),
(2015, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un cuento'),
(2016, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un sombrero'),
(2017, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería una casa'),
(2018, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería una bicicleta'),
(2019, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un perro'),
(2020, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un gato'),
(2021, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un pez'),
(2022, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un pájaro'),
(2023, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un conejo'),
(2024, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un ratón'),
(1990, 'Mem Fox', 'HarperCollins', 'La gallina que no quería poner huevos'),
(1991, 'Kevin Henkes', 'Greenwillow Books', 'Lilly y su bolso de plástico morado'),
(1992, 'Eric Carle', 'Kókinos', 'De la cabeza a los pies'),
(1993, 'Bernard Waber', 'Houghton Mifflin Harcourt', 'Lyle, Lyle, cocodrilo'),
(1994, 'Leo Lionni', 'Kókinos', 'Pez, pez, pez'),
(1995, 'Laura Numeroff', 'HarperCollins', 'Si le das un pancake a un cerdo'),
(1996, 'Mo Willems', 'Hyperion Books', 'El pato que no quería volar'),
(1997, 'Karma Wilson', 'Simon & Schuster Books for Young Readers', 'Oso está dormido'),
(1998, 'Doreen Cronin', 'Simon & Schuster Books for Young Readers', 'Clic, Clac, Muu: Vacas que escriben a máquina'),
(1999, 'Mem Fox', 'HarperCollins', '¿Dónde está mi mamá?'),
(2000, 'Robert Munsch', 'Annick Press', 'El papel de los colores'),
(2001, 'David Shannon', 'Scholastic', '¡Grita, David!'),
(2002, 'Todd Parr', 'Little, Brown Books for Young Readers', 'El libro del amor'),
(2003, 'Mies van Hout', 'Lemniscaat', 'Yo soy un animal'),
(2004, 'Kobi Yamada', 'Compendium', '¿Qué harías con un problema?'),
(2005, 'Oliver Jeffers', 'HarperCollins', 'El niño de los lápices de colores'),
(2006, 'Oliver Jeffers', 'HarperCollins', 'El niño que no quería dormir'),
(2007, 'Oliver Jeffers', 'HarperCollins', 'El niño que no quería irse a la cama'),
(2008, 'Oliver Jeffers', 'HarperCollins', 'El niño que amaba los libros'),
(2009, 'Oliver Jeffers', 'HarperCollins', 'El niño que se encontró con un dinosaurio'),
(2010, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería volar'),
(2011, 'Oliver Jeffers', 'HarperCollins', 'El niño que no quería ser un perro'),
(2012, 'Oliver Jeffers', 'HarperCollins', 'El niño que no quería un amigo'),
(2013, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería una nube'),
(2014, 'Oliver Jeffers', 'HarperCollins', 'El niño que no quería comer'),
(2015, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un cuento'),
(2016, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un sombrero'),
(2017, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería una casa'),
(2018, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería una bicicleta'),
(2019, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un perro'),
(2020, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un gato'),
(2021, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un pez'),
(2022, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un pájaro'),
(2023, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un conejo'),
(2024, 'Oliver Jeffers', 'HarperCollins', 'El niño que quería un ratón');